### ISSUE TITLE
Feature Request: string update

### ISSUE THREAD

**Issue by TheSamDickey** [bobsparadox/seti-black#1]
Hello!  Just wanted to say first of all, thank you for making this color scheme :D, I love it!  Recently got an LG C1 as my primary display, and this theme looks stunning.

I was wondering if you could make a minor update to fix the color where it says `${link.Link}`:
![image](https://user-images.githubusercontent.com/62564563/142715800-b2c34872-e63d-47c9-b802-9f9ed866c18f.png)

Here's how monokai looks in this example:
![image](https://user-images.githubusercontent.com/62564563/142715830-b862c997-9522-48ad-9cce-0201a070e51c.png)

The current state of the theme makes it all look like a string, which made me second guess myself haha.  Thank you again for making this!

**Comment by bobsparadox** [comment]
I believe I've fixed this in the latest update. Sorry it took so long to get to. I hope you're still enjoying the theme.

**Comment by bobsparadox** [comment]
Resolved in e3ee49e5c809cd3c4153ebcbaed34b4146d33263
